"""Tests for scripts/regenerate_verdicts.py hand-written section preservation.

Tests the fix for a silent data-loss bug where prose appearing after the
<!-- HAND-WRITTEN, PRESERVED --> marker but before any ## headers would be
lost on regeneration (e.g., the "The sign flips in 2020..." passage in H3).

The guard function raises ValueError if content shrinks, preventing future loss.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

_SCRIPT_PATH = (
    Path(__file__).resolve().parent.parent / "scripts" / "regenerate_verdicts.py"
)
_spec = importlib.util.spec_from_file_location("regenerate_verdicts", _SCRIPT_PATH)
assert _spec is not None and _spec.loader is not None
regen = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = regen
_spec.loader.exec_module(regen)


class TestExtractHandwrittenSections:
    """Tests for extract_handwritten_sections() function."""

    def test_regression_unheaded_prose_preserved(self, tmp_path: Path) -> None:
        """Test the regression: prose directly after marker before any header.

        This test MUST FAIL against the buggy implementation and PASS after the fix.
        Prose that appears between <!-- HAND-WRITTEN, PRESERVED --> and the first
        ## header should be preserved, not silently dropped.
        """
        # Create a file with unheaded prose after the marker
        verdict_file = tmp_path / "verdict.md"
        content = """<!-- Generated by hypothesis runner -->

# Some Hypothesis

Some results here.

<!-- HAND-WRITTEN, PRESERVED -->

This is an unheaded paragraph that appears directly after the marker.
It should be preserved in the extracted sections.
This was the bug: it was silently dropped.

## Reconnaissance cross-check

This is a headed section and should also be preserved.
"""
        verdict_file.write_text(content)

        # Extract sections
        sections = regen.extract_handwritten_sections(verdict_file)

        # The unheaded prose should be in the preserved content
        assert sections, "Should have extracted preserved sections"
        assert "__all_preserved__" in sections
        preserved = sections["__all_preserved__"]

        # Verify the unheaded prose is there
        assert "This is an unheaded paragraph" in preserved
        assert "This was the bug" in preserved
        # And the headed section should also be there
        assert "## Reconnaissance cross-check" in preserved
        assert "This is a headed section" in preserved

    def test_headed_sections_still_preserved(self, tmp_path: Path) -> None:
        """Test that ## -headed sections continue to be preserved (non-regression)."""
        verdict_file = tmp_path / "verdict.md"
        content = """<!-- Generated by hypothesis runner -->

# Some Hypothesis

Results.

<!-- HAND-WRITTEN, PRESERVED -->

## Reconnaissance cross-check

This reconnaissance check confirms the result.

## Conclusion

The hypothesis is verified.
"""
        verdict_file.write_text(content)

        sections = regen.extract_handwritten_sections(verdict_file)
        assert sections
        assert "__all_preserved__" in sections
        preserved = sections["__all_preserved__"]

        # Both headers should be there
        assert "## Reconnaissance cross-check" in preserved
        assert "## Conclusion" in preserved
        # And the content under each
        assert "This reconnaissance check" in preserved
        assert "The hypothesis is verified" in preserved

    def test_both_unheaded_and_headed_sections_ordered(self, tmp_path: Path) -> None:
        """Test a document with both unheaded prose and headed sections."""
        verdict_file = tmp_path / "verdict.md"
        content = """<!-- Generated -->

Results here.

<!-- HAND-WRITTEN, PRESERVED -->

Some unheaded prose at the start of the preserved section.
This appears before any headers.

## First Section

Content of the first section.

## Second Section

Content of the second section.

More content in the second section.
"""
        verdict_file.write_text(content)

        sections = regen.extract_handwritten_sections(verdict_file)
        assert sections
        preserved = sections["__all_preserved__"]

        # Verify order is preserved: unheaded prose first, then sections
        unheaded_idx = preserved.find("Some unheaded prose")
        first_section_idx = preserved.find("## First Section")
        second_section_idx = preserved.find("## Second Section")

        assert unheaded_idx >= 0
        assert first_section_idx > unheaded_idx, "First section should come after unheaded prose"
        assert second_section_idx > first_section_idx, "Second section should come after first"

    def test_no_preserved_marker_returns_empty(self, tmp_path: Path) -> None:
        """Test that a file without the preserved marker returns empty dict."""
        verdict_file = tmp_path / "verdict.md"
        content = """<!-- Generated -->

# Some Hypothesis

Results but no preserved sections.

## Regular Section

This is not marked as preserved.
"""
        verdict_file.write_text(content)

        sections = regen.extract_handwritten_sections(verdict_file)
        assert sections == {}

    def test_nonexistent_file_returns_empty(self, tmp_path: Path) -> None:
        """Test that a nonexistent file returns empty dict without crashing."""
        nonexistent = tmp_path / "does_not_exist.md"
        sections = regen.extract_handwritten_sections(nonexistent)
        assert sections == {}

    def test_preserved_marker_but_no_content(self, tmp_path: Path) -> None:
        """Test that marker with no content after it returns empty dict."""
        verdict_file = tmp_path / "verdict.md"
        content = """<!-- Generated -->

# Results

<!-- HAND-WRITTEN, PRESERVED -->"""
        verdict_file.write_text(content)

        sections = regen.extract_handwritten_sections(verdict_file)
        assert sections == {}


class TestPreservedContentGuard:
    """Tests for _verify_preserved_content_not_lost() guard function."""

    def test_guard_passes_when_content_preserved(self, tmp_path: Path) -> None:
        """Test that guard does not raise when content is preserved."""
        original_file = tmp_path / "original.md"
        original_file.write_text("""<!-- HAND-WRITTEN, PRESERVED -->

Some important preserved content that must not be lost.

## A Section

More content.
""")

        new_output = """<!-- Generated header -->

# New Results

<!-- HAND-WRITTEN, PRESERVED -->

Some important preserved content that must not be lost.

## A Section

More content.
"""

        # Should not raise
        regen._verify_preserved_content_not_lost(original_file, new_output)

    def test_guard_raises_when_marker_removed(self, tmp_path: Path) -> None:
        """Test that guard raises when preserved marker is removed."""
        original_file = tmp_path / "original.md"
        original_file.write_text("""<!-- HAND-WRITTEN, PRESERVED -->

Important content here.
""")

        new_output = "<!-- Generated -->\n\nNew results without any preserved section."

        with pytest.raises(ValueError, match="preserved marker removed"):
            regen._verify_preserved_content_not_lost(original_file, new_output)

    def test_guard_raises_when_content_shrinks(self, tmp_path: Path) -> None:
        """Test that guard raises when preserved content shrinks significantly."""
        original_file = tmp_path / "original.md"
        original_file.write_text("""<!-- HAND-WRITTEN, PRESERVED -->

This is a long paragraph with important content that should be preserved.
It spans multiple lines and contains substantial information.
This is the bug scenario: it gets dropped and only partially reappears.
""")

        # New output with most of the preserved content missing
        new_output = """<!-- Generated -->

# Results

<!-- HAND-WRITTEN, PRESERVED -->

This is a long
"""

        with pytest.raises(ValueError, match="preserved content shrank"):
            regen._verify_preserved_content_not_lost(original_file, new_output)

    def test_guard_passes_with_original_nonexistent(self, tmp_path: Path) -> None:
        """Test that guard does not raise if original file never existed."""
        nonexistent = tmp_path / "never_existed.md"
        new_output = "<!-- HAND-WRITTEN, PRESERVED -->\n\nSome content"

        # Should not raise
        regen._verify_preserved_content_not_lost(nonexistent, new_output)

    def test_guard_passes_if_original_had_no_preserved_marker(
        self, tmp_path: Path
    ) -> None:
        """Test that guard does not raise if original had no preserved marker."""
        original_file = tmp_path / "original.md"
        original_file.write_text("<!-- Generated -->\n\nSome results.")

        new_output = """<!-- Generated -->

# Results

<!-- HAND-WRITTEN, PRESERVED -->

New preserved content (original didn't have any).
"""

        # Should not raise, since original had nothing to lose
        regen._verify_preserved_content_not_lost(original_file, new_output)

    def test_guard_passes_with_small_whitespace_shrinkage(
        self, tmp_path: Path
    ) -> None:
        """Test that guard tolerates small shrinkage due to whitespace normalization."""
        original_file = tmp_path / "original.md"
        original_file.write_text("""<!-- HAND-WRITTEN, PRESERVED -->

Some content here.
""")

        # Shrinks slightly due to whitespace normalization (< 10 chars or < 1%)
        new_output = """<!-- HAND-WRITTEN, PRESERVED -->

Some content here."""

        # Should not raise: loss is < 10 chars
        regen._verify_preserved_content_not_lost(original_file, new_output)


class TestIntegrationRoundTrip:
    """Integration tests: full regeneration cycle preserves content."""

    def test_full_roundtrip_preserves_unheaded_prose(self, tmp_path: Path) -> None:
        """Test complete regeneration cycle preserves unheaded prose.

        Simulates calling extract, building new output, and verifying guard.
        """
        # Create an original verdict file with unheaded prose
        original_file = tmp_path / "verdict.md"
        original_file.write_text("""<!-- Generated header -->

# Hypothesis Results

The edge is 1.5 bps, t-stat is 2.3.

<!-- HAND-WRITTEN, PRESERVED -->

The sign flips in 2020 and stays flipped, so the near-zero pooled number
is not a small effect -- it is two opposing regimes cancelling.

## Reconnaissance cross-check

Independent oracle result confirms this.
""")

        # Simulate extraction and regeneration
        extracted = regen.extract_handwritten_sections(original_file)
        assert "__all_preserved__" in extracted

        # Build new output with the preserved content
        new_output = """<!-- Generated header -->

# Hypothesis Results

The edge is 2.1 bps, t-stat is 2.8. (Updated results)

<!-- HAND-WRITTEN, PRESERVED -->

""" + extracted["__all_preserved__"]

        # Guard should pass
        regen._verify_preserved_content_not_lost(original_file, new_output)

        # And the unheaded prose should be in the new output
        assert "The sign flips in 2020" in new_output
        assert "Reconnaissance cross-check" in new_output

    def test_h3_real_world_scenario(self, tmp_path: Path) -> None:
        """Test the actual H3 scenario that broke: two-paragraph explanation.

        This is the real-world bug: "The sign flips in 2020 and stays flipped..."
        passage was silently lost and had to be restored by hand. This test
        ensures it would be preserved on the next regeneration.
        """
        # Simulate the actual H3 verdict.md structure (lines 35-78 of real file)
        original_file = tmp_path / "h3_verdict.md"
        h3_content = (
            "<!-- nifty_quant.research.hypotheses.h3_intraday_xsec_reversal.run_h3\n"
            "     all_equity (149 names), 2018-01-01..2025-07-31; "
            "last 12 months held out, NOT read.\n"
            "     Panel: 701,863 rows x 149 symbols, reduced to "
            "a 2-rows-per-session checkpoint panel.\n"
            "     Module verified against 52 tests (47 written independently\n"
            "     pre-implementation by two authors who did not read "
            "each other's file, + 5 internal).\n"
            "     Regenerated by the lead from a separate script, "
            "not transcribed from the implementing agent's report. -->\n\n"
            "# H3_intraday_xsec_reversal\n\n"
            "**Verdict:** KILLED (INCOMPLETE: one or more "
            "criteria NOT_EVALUATED)\n\n"
            "## Kill Criteria\n\n"
            "- 1. Edge criterion: FAIL (edge=1.21 bps, 2x hurdle=16.53 bps)\n\n"
            "## Per-year spread (bps)\n\n"
            "| 2018 | 2019 | 2020 | 2021 | 2022 | 2023 | 2024 | 2025 |\n"
            "|---|---|---|---|---|---|---|---|\n"
            "| -12.60 | -13.33 | +1.30 | +5.96 | +12.34 | +7.27 "
            "| +6.57 | -1.07 |\n"
            "<!-- HAND-WRITTEN, PRESERVED -->\n\n"
            "The sign flips in 2020 and stays flipped, so the "
            "near-zero pooled number\n"
            "is not a small effect -- it is two opposing regimes cancelling. "
            "Neither\nregime clears the gate on its own.\n\n"
            "## Reconnaissance cross-check\n\n"
            "This is the independent oracle that caught H2's 25,000x error, "
            "so it is\nrecorded explicitly. Reconnaissance "
            "(separate code path, same window)\nreported extensive analysis "
            "here.\n\n"
            "## Why this was built after the answer was known\n\n"
            "Reconnaissance was already decisive. The module exists for "
            "the audit trail:\na verdict nobody can reproduce is not a "
            "verdict.\n\n"
            "## Conclusion\n\n"
            "Fails on all four counts the hypothesis could fail on: "
            "magnitude ~14x\nshort of the gate, t = 1.04, sign unstable "
            "across years, and the sign\nis POSITIVE.\n"
        )
        original_file.write_text(h3_content)

        # Extract the preserved sections
        extracted = regen.extract_handwritten_sections(original_file)
        assert "__all_preserved__" in extracted
        preserved = extracted["__all_preserved__"]

        # Verify the critical unheaded prose is in there
        assert "The sign flips in 2020" in preserved
        assert "two opposing regimes cancelling" in preserved
        # And the sections too
        assert "## Reconnaissance cross-check" in preserved
        assert "## Why this was built after the answer was known" in preserved
        assert "## Conclusion" in preserved

        # Simulate regeneration with updated results
        new_output_header = (
            "<!-- nifty_quant.research.hypotheses.h3_intraday_xsec_reversal.run_h3\n"
            "     all_equity (149 names), 2018-01-01..2025-07-31; "
            "last 12 months held out, NOT read.\n"
            "     Panel: 701,863 rows x 149 symbols, reduced to "
            "a 2-rows-per-session checkpoint panel.\n"
            "     Module verified against 52 tests. -->\n\n"
            "# H3_intraday_xsec_reversal\n\n"
            "**Verdict:** KILLED\n\n"
            "## Kill Criteria\n\n"
            "- 1. Edge criterion: FAIL (edge=1.30 bps) [NEW RESULTS]\n\n"
            "## Per-year spread (bps)\n\n"
            "[Updated table here]\n\n"
            "<!-- HAND-WRITTEN, PRESERVED -->\n\n"
        )
        new_output = new_output_header + preserved

        # Verify no content was lost
        regen._verify_preserved_content_not_lost(original_file, new_output)

        # Verify the critical passage is still there
        assert "The sign flips in 2020" in new_output
