"""Suite A for specs/portfolio_construction.md (Spec G -- portfolio construction),
written FROM THE SPEC ALONE per CLAUDE.md rule 1. Suite B is written independently by a
different agent from the same spec text, without seeing this file or vice versa; any
disagreement between the two suites is itself a finding to be triaged by the lead.

No implementation exists yet for G1 (the weighting-scheme registry) or G3 (the
pre-registered scheme comparison / recent-window promotion gate). These tests are
DELIBERATELY RED at HEAD: assumed-future names are imported inside the body of the one
test function that needs them (never at module level), so a missing module fails a single
test at EXECUTION time rather than failing COLLECTION for the whole file.

Obligations 7 and 8 (VolTargetSizer wiring) need no assumed import at all: they are
correctly red today via a REAL exception -- `engine.py` calls `config.sizer.to_shares(...)`
without `sigma=`/`corr=`, so substituting a `VolTargetSizer` raises
`ValueError("sigma is required")` on the first decision row.

Spec defects found (recorded here per rule 1, not silently resolved and not fixed in
specs/portfolio_construction.md, which this suite does not touch):

1. G1 declares every scheme as a pure `(signal, sigma, corr, mask) -> weights` function (a
   bare array return), but obligation 2 requires each scheme to "report when the clip
   binds" -- a boolean that cannot be expressed in a bare-array return. Internal
   contradiction. Resolution used below: a shared `apply_weight_scheme(name, ...,
   max_weight, gross)` helper performs the clip-and-report step for all seven schemes
   uniformly (mirroring how `VolTargetSizer`/`GrossNotionalSizer` already share
   `_finalize_shares_shared`), rather than making it each scheme's own responsibility.
2. G1's `mask` argument is singular, but obligation 3 requires the present/tradable
   DISTINCTION (repo rule 7) to be enforced, which a single mask argument cannot encode by
   itself. Resolution used below: the registry's mask parameter IS the tradable mask;
   schemes never see a present-only mask. This only actually tests present/tradable
   handling at the unit boundary -- an end-to-end check would additionally need to confirm
   whichever future caller constructs `tradable` never leaks a present-only name into it,
   which is out of scope for a scheme-level test.
3. Obligation 1 says weights sum "to the declared gross" but G1 names no `gross` parameter
   anywhere in the scheme signature. Resolution used below: `apply_weight_scheme(...,
   gross=1.0)` scales the raw per-scheme output so `sum(abs(weights)) == gross`.
4. Obligation 6 asserts `covariance_aware` "degenerates EXACTLY to inverse_vol" under a
   diagonal covariance, but the spec never defines `covariance_aware`'s actual formula --
   only its degenerate-case behaviour. `test_o6_...` below can therefore only check the
   literal boundary condition (equal output when `corr=0.0`), not validate any particular
   general covariance_aware algorithm.
5. `BacktestResult` at HEAD has no `sigma_portfolio_ann` / `vol_target_achieved` /
   `clip_binding` field at all. `test_o7_...`/`test_o8_...` below ASSUME these become
   per-decision-row `np.ndarray` fields once `VolTargetSizer` is wired, mirroring how
   `turnover` is already a per-decision-row `np.ndarray` -- this is an assumption about the
   wiring's shape, not a certainty, and is called out again inline at each test.
6. Obligations 11-13 below were added mid-task by the lead as a CONFIRMED, MEASURED defect
   (not present in the original spec text, and not hypothetical): `run_tilt`
   (`research/tilt.py` ~line 636) sets `config_hash = contract.contract_hash`, which hashes
   only the six `ResearchContract` sections plus `seed` and never depends on the `TiltConfig`
   actually run. Combined with `TrialRegistry`'s `UNIQUE(config_hash, split_id)` constraint,
   `INSERT OR IGNORE` semantics, and `run_tilt`'s hard-coded `split_id="full"`, two different
   `TiltConfig`s recorded against the same contract/registry silently collapse to one row.
   Since `n_trials()`/`registry.all()` feed `effective_n_trials`/deflated Sharpe/PBO directly,
   this understates the trial count and makes a multiple-testing correction too permissive --
   exactly the mechanism a spurious scheme-comparison "winner" would be manufactured by.
   `test_o12_...`/`test_o13_...` are EXPECTED TO FAIL TODAY for this reason; that is the
   point, not a mistake.

Generated by gpt-5.6-luna (effort xhigh) in three scoped calls (schemes, engine/G3, tilt
regression), assembled and reviewed by the delegating agent (worker-luna). Not hand-written.
"""

from __future__ import annotations

import dataclasses
import datetime

import numpy as np
import pytest

from nifty_quant.backtest.engine import BacktestConfig, run_backtest
from nifty_quant.backtest.metrics import deflated_sharpe, effective_n_trials
from nifty_quant.backtest.portfolio import VolTargetSizer
from nifty_quant.features.core import sigma_risk
from nifty_quant.research.registry import TrialRegistry
from nifty_quant.research.tilt import TiltConfig, run_tilt
from tests.contract_fixtures import minimal_contract
from tests.test_engine import N_ROWS, N_SYM, ConstantWeightStrategy, make_panel
from tests.test_tilt_a import _build_panel, _flat_row

# =========================================================================
# G1 -- weighting-scheme registry (obligations 1-6)
# =========================================================================


def test_o1_each_scheme_weights_sum_to_declared_gross():
    """RED at HEAD: This catches any registered weighting scheme that fails to normalize
    its unclipped output to the declared gross of 1.0."""
    from nifty_quant.backtest.weighting import WEIGHT_SCHEME_REGISTRY, apply_weight_scheme

    signal = np.array([2.0, -1.5, 0.5, -0.2, 1.0, -0.8], dtype=np.float64)
    sigma = np.array([0.15, 0.30, 0.20, 0.45, 0.10, 0.25], dtype=np.float64)
    tradable = np.ones(signal.shape, dtype=bool)

    for name in WEIGHT_SCHEME_REGISTRY:
        result = apply_weight_scheme(
            name,
            signal=signal,
            sigma=sigma,
            corr=0.2,
            tradable=tradable,
            gross=1.0,
            max_weight=1.0,
        )
        weights = np.asarray(result.weights, dtype=np.float64)
        assert np.sum(np.abs(weights)) == pytest.approx(1.0)


def test_o2_clip_binds_and_is_reported():
    """RED at HEAD: This catches inverse-volatility clipping that either allows a weight
    above max_weight or reports a constant clip_binding flag regardless of whether the
    clip actually moved anything."""
    from nifty_quant.backtest.weighting import apply_weight_scheme

    signal = np.array([1.0, -0.8, 0.6, -1.1, 0.9, -0.7], dtype=np.float64)
    sigma = np.array([0.02, 0.30, 0.25, 0.28, 0.20, 0.35], dtype=np.float64)
    tradable = np.ones(signal.shape, dtype=bool)

    clipped = apply_weight_scheme(
        "inverse_vol",
        signal=signal,
        sigma=sigma,
        corr=0.2,
        tradable=tradable,
        gross=1.0,
        max_weight=0.15,
    )
    clipped_weights = np.asarray(clipped.weights, dtype=np.float64)
    assert np.all(np.abs(clipped_weights) <= 0.15 + 1e-9)
    assert clipped.clip_binding is True

    unclipped = apply_weight_scheme(
        "inverse_vol",
        signal=signal,
        sigma=sigma,
        corr=0.2,
        tradable=tradable,
        gross=1.0,
        max_weight=1.0,
    )
    assert unclipped.clip_binding is False


def test_o3_present_not_tradable_never_gets_weight():
    """RED at HEAD: This catches a scheme that conflates present and tradable bars (repo
    rule 7) by assigning a nonzero weight to a name that is present but non-tradable."""
    from nifty_quant.backtest.weighting import WEIGHT_SCHEME_REGISTRY

    present = np.array([True, True, True, True, True], dtype=bool)  # noqa: F841 -- kept
    # to make the present/tradable distinction explicit at the call site even though only
    # `tradable` is ever passed to a scheme (repo rule 7: never conflate the two masks).
    tradable = np.array([True, True, False, True, True], dtype=bool)
    signal = np.array([1.2, -0.7, 0.4, 1.8, -1.1], dtype=np.float64)
    sigma = np.array([0.16, 0.31, 0.24, 0.42, 0.13], dtype=np.float64)

    for name in WEIGHT_SCHEME_REGISTRY:
        weights = WEIGHT_SCHEME_REGISTRY[name](signal, sigma, 0.1, tradable)
        weights = np.asarray(weights, dtype=np.float64)
        assert weights[2] == 0.0


def test_o4_inverse_vol_zero_sigma_uses_floor_not_inf():
    """RED at HEAD: This catches inverse-volatility weighting that divides by a zero sigma
    without applying sigma_risk's measured floor first."""
    from nifty_quant.backtest.weighting import WEIGHT_SCHEME_REGISTRY

    signal = np.array([1.0, -0.5, 0.8, -1.2, 0.6], dtype=np.float64)
    sigma = np.array([0.0, 0.20, 0.30, 0.15, 0.40], dtype=np.float64)
    tradable = np.ones(signal.shape, dtype=bool)

    weights = WEIGHT_SCHEME_REGISTRY["inverse_vol"](signal, sigma, 0.0, tradable)
    weights = np.asarray(weights, dtype=np.float64)
    assert np.all(np.isfinite(weights))

    expected_raw = 1.0 / sigma_risk(sigma)
    normalized_weights = weights / np.sum(np.abs(weights))
    normalized_expected = expected_raw / np.sum(np.abs(expected_raw))
    np.testing.assert_allclose(
        normalized_weights, normalized_expected, rtol=1e-12, atol=1e-12
    )

    # Contrast: the naive, unfloored division WOULD have produced inf at index 0 -- this
    # is what makes the floor's necessity explicit rather than merely asserted by prose.
    with np.errstate(divide="ignore"):
        assert not np.isfinite(1.0 / sigma[0])


def test_o5_risk_parity_equal_vol_zero_corr_is_exactly_equal_weight():
    """RED at HEAD: This catches risk-parity weighting that lets a varying signal disturb
    equal weights when all volatilities are equal and correlation is zero -- the one input
    for which the correct closed-form answer is unambiguous."""
    from nifty_quant.backtest.weighting import WEIGHT_SCHEME_REGISTRY

    signal = np.array([1.4, -0.6, 0.2, 1.1, -1.3, 0.7], dtype=np.float64)
    sigma = np.full(6, 0.22, dtype=np.float64)
    tradable = np.ones(signal.shape, dtype=bool)

    weights = WEIGHT_SCHEME_REGISTRY["risk_parity"](signal, sigma, 0.0, tradable)
    weights = np.asarray(weights, dtype=np.float64)

    for weight in weights[1:]:
        assert weight == pytest.approx(weights[0], rel=1e-12, abs=1e-12)


def test_o6_covariance_aware_diagonal_covariance_matches_inverse_vol():
    """RED at HEAD: This catches covariance-aware weighting that does not match
    inverse-volatility weighting at the ONE boundary condition the spec actually defines
    (a diagonal covariance) -- the spec never specifies covariance_aware's general
    algorithm, so this is the only property that can be tested against the spec alone."""
    from nifty_quant.backtest.weighting import WEIGHT_SCHEME_REGISTRY

    signal = np.array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9], dtype=np.float64)
    sigma = np.array([0.10, 0.45, 0.22, 0.33, 0.15, 0.28], dtype=np.float64)
    tradable = np.ones(signal.shape, dtype=bool)

    covariance_aware_weights = WEIGHT_SCHEME_REGISTRY["covariance_aware"](
        signal, sigma, 0.0, tradable
    )
    inverse_vol_weights = WEIGHT_SCHEME_REGISTRY["inverse_vol"](
        signal, sigma, 0.0, tradable
    )

    np.testing.assert_allclose(
        np.asarray(covariance_aware_weights, dtype=np.float64),
        np.asarray(inverse_vol_weights, dtype=np.float64),
    )


# =========================================================================
# G2/G3 -- VolTargetSizer wiring and the pre-registered scheme comparison
# (obligations 7-10)
# =========================================================================


def test_o7_vol_target_sizer_reachable_and_sigma_portfolio_ann_populated():
    """RED at HEAD: the backtest engine cannot reach VolTargetSizer with portfolio sigma
    (engine.py passes no sigma=/corr=) and therefore cannot populate a positive
    portfolio-volatility diagnostic; currently raises ValueError("sigma is required")."""
    t = np.arange(N_ROWS, dtype=np.float64)
    symbol_phase = np.arange(N_SYM, dtype=np.float64)
    close = (100.0 + 5.0 * np.sin(t[:, None] / 37.0 + symbol_phase[None, :])).astype(
        np.float64
    )
    panel = make_panel(close)
    strategy = ConstantWeightStrategy(
        ConstantWeightStrategy.Params(weights=(0.05, -0.03, 0.02))
    )
    config = BacktestConfig(sizer=VolTargetSizer(target_vol_ann=0.15))

    # ASSUMPTION (spec defect 5 above): once VolTargetSizer is wired, BacktestResult grows
    # per-decision-row np.ndarray fields sigma_portfolio_ann, vol_target_achieved, and
    # clip_binding, mirroring turnover.
    result = run_backtest(strategy, panel, config, contract=minimal_contract())

    assert result.equity_curve.size > 0
    assert bool(
        np.any(np.isfinite(result.sigma_portfolio_ann) & (result.sigma_portfolio_ann > 0.0))
    )


def test_o8_clip_that_breaks_target_is_reported_through_engine():
    """RED at HEAD: the backtest engine cannot execute a clipped volatility target or
    report -- through the engine, not just the sizer in isolation -- that clipping kept
    achieved volatility below the declared target; currently raises the same ValueError as
    test_o7 before any decision is even sized."""
    t = np.arange(N_ROWS, dtype=np.float64)
    symbol_phase = np.arange(N_SYM, dtype=np.float64)
    close = (100.0 + 5.0 * np.sin(t[:, None] / 37.0 + symbol_phase[None, :])).astype(
        np.float64
    )
    panel = make_panel(close)
    strategy = ConstantWeightStrategy(
        ConstantWeightStrategy.Params(weights=(0.05, -0.03, 0.02))
    )
    config = BacktestConfig(sizer=VolTargetSizer(target_vol_ann=5.0, max_weight=0.05))

    # ASSUMPTION (spec defect 5 above): same as test_o7.
    result = run_backtest(strategy, panel, config, contract=minimal_contract())

    assert bool(np.any(result.clip_binding))
    for row in np.flatnonzero(result.clip_binding):
        assert result.vol_target_achieved[row] < config.sizer.target_vol_ann


def test_o9_effective_n_trials_across_schemes_is_measured_below_seven():
    """RED at HEAD: this catches a scheme comparison that scores all seven schemes as if
    independent (n_eff ~ 7) despite the genuine shared structure the spec names
    (inverse_vol/z_over_vol share a denominator, rank_weight/z_weight share an ordering),
    and separately catches a comparison that never registers its trials against a
    ResearchContract at all."""
    from nifty_quant.backtest.weighting import WEIGHT_SCHEME_REGISTRY

    n_names = 5
    n_days = 30
    # Plain, non-cherry-picked seed (rule 9: never tune a seed to make a statistical
    # assertion pass).
    rng = np.random.default_rng(0)

    scheme_names = tuple(sorted(WEIGHT_SCHEME_REGISTRY))
    assert len(scheme_names) == 7

    base_sigma = np.linspace(0.15, 0.40, n_names, dtype=np.float64)
    day_index = np.arange(n_days, dtype=np.float64)
    day_scale = 1.0 + 0.08 * np.sin(day_index / 5.0)
    sigma_noise = 0.01 * rng.standard_normal((n_days, n_names))
    sigma = (day_scale[:, None] * base_sigma[None, :] + sigma_noise).astype(np.float64)

    latent_signal = rng.standard_normal(n_days).astype(np.float64)
    signal_noise = rng.standard_normal((n_days, n_names)).astype(np.float64)
    signal = (latent_signal[:, None] + 0.15 * signal_noise).astype(np.float64)

    common_forward = rng.standard_normal(n_days).astype(np.float64)
    return_loadings = np.linspace(0.9, 1.1, n_names, dtype=np.float64)
    forward_noise = rng.standard_normal((n_days, n_names)).astype(np.float64)
    forward_return = (
        0.01 * common_forward[:, None] * return_loadings[None, :]
        + 0.002 * signal_noise
        + 0.002 * forward_noise
    ).astype(np.float64)

    tradable = np.ones(n_names, dtype=bool)
    trial_returns = np.empty((n_days, len(scheme_names)), dtype=np.float64)
    for day in range(n_days):
        for scheme_index, name in enumerate(scheme_names):
            # Causal: day d's weights use ONLY day d's own signal/sigma, never day d's or
            # any later day's forward return.
            weights = np.asarray(
                WEIGHT_SCHEME_REGISTRY[name](
                    signal[day], sigma[day], corr=0.1, tradable=tradable
                ),
                dtype=np.float64,
            )
            trial_returns[day, scheme_index] = float(weights @ forward_return[day])

    n_trials_eff = effective_n_trials(trial_returns)
    assert np.isfinite(n_trials_eff)
    assert n_trials_eff > 1.0
    assert n_trials_eff < 7.0  # 7 is a structural count of schemes, not a tuned threshold.

    contract = minimal_contract(
        validation={"scheme": "test", "holdout_intent": "never", "n_planned_trials": 7}
    )
    for expected, _name in enumerate(scheme_names, start=1):
        assert contract.register_trial() == expected

    with pytest.raises(ValueError):
        contract.register_trial()


def test_o10_promotion_uses_recent_window_not_pooled():
    """RED at HEAD: this catches a promotion decision that reads the pooled deflated
    Sharpe instead of (or in addition to) the recent-window figure -- exactly the H2
    pooled-vs-recent regression the spec cites.

    MIGRATED by the lead per AMENDMENT 5 (2026-08-31): this suite's original guess
    (`portfolio_sweep.evaluate_scheme_promotion(pooled, recent, threshold) -> bool`) lost
    the A3.5 adjudication to the returns-based interface, which is strictly stronger --
    a caller cannot hand it a pooled number relabelled as recent. Fixture, seed, and the
    pooled-passes/recent-fails self-checks are unchanged.

    AMENDMENT 6: the original self-checks (pooled > 0, recent <= 0) assumed signed-Sharpe
    semantics; deflated_sharpe is a CDF in [0, 1], so they were impossible and had never
    run (the import used to fail first). Early mean raised 0.004 -> 0.006 so the pooled
    window CLEARS the repo's actual 0.95 DSR bar (measured 0.9893) while the recent window
    fails it (0.0044); deterministic under the fixed seed."""
    from nifty_quant.research.feature_sweep import DEFLATED_SHARPE_THRESHOLD_DEFAULT
    from nifty_quant.research.portfolio_comparison import evaluate_scheme_promotion

    rng = np.random.default_rng(1)
    early_returns = rng.normal(0.006, 0.01, 48).astype(np.float64)
    recent_returns = rng.normal(-0.006, 0.01, 12).astype(np.float64)
    whole_series = np.concatenate((early_returns, recent_returns)).astype(np.float64)

    deflated_sharpe_pooled = deflated_sharpe(whole_series, sr0=0.0)
    deflated_sharpe_recent = deflated_sharpe(whole_series[-12:], sr0=0.0)

    # Intermediate facts asserted explicitly so this fails loudly, with a clear message, if
    # the fixture itself stops producing the intended pooled-passes/recent-fails contrast.
    assert deflated_sharpe_pooled > DEFLATED_SHARPE_THRESHOLD_DEFAULT
    assert deflated_sharpe_recent < DEFLATED_SHARPE_THRESHOLD_DEFAULT

    day_offsets = np.arange(0, whole_series.shape[0] + 1, 1, dtype=np.int64)
    result = evaluate_scheme_promotion(
        returns=whole_series, day_offsets=day_offsets, recent_n_sessions=12
    )
    assert result.promoted is False


# =========================================================================
# Addendum (obligations 11-13) -- confirmed run_tilt config_hash / registry defect.
# Every API used below is REAL and already exists at HEAD; these are regression tests
# pinning a measured defect, not spec-first red-by-absence tests.
# =========================================================================


@pytest.mark.parametrize(
    "field_name, alt_value",
    [
        ("entry_hhmm", "09:17"),
        ("exit_hhmm", "15:19"),
        ("capital", 900_000.0),
        ("tilt", "mild"),
        ("smoothing", 0.5),
        ("rebalance_every", 2),
        ("universe", "all_equity_variant"),
        ("continuous_only", True),
        ("seed", 1),
    ],
)
def test_o11_config_hash_differs_when_any_tilt_param_differs(tmp_path, field_name, alt_value):
    """RED at HEAD: run_tilt records an IDENTICAL config_hash when any one of these
    TiltConfig parameters changes, because config_hash is set to contract.contract_hash,
    which never depends on TiltConfig at all. NOTE: this parametrize list is a
    hand-maintained enumeration -- a brand-new TiltConfig field remains a residual gap in
    this test until someone adds its own entry here."""
    dates = [datetime.date(2022, 1, 3) + datetime.timedelta(days=i) for i in range(5)]
    sessions = []
    for date in dates:
        entry_row = _flat_row(100.0)
        exit_row = entry_row + 0.01
        sessions.append(
            (
                date,
                {
                    "09:16": entry_row,
                    "09:17": entry_row.copy(),
                    "15:19": exit_row,
                    "15:20": exit_row.copy(),
                },
            )
        )
    panel = _build_panel(sessions)

    base_config = TiltConfig(
        start=dates[0],
        end=dates[-1],
        entry_hhmm="09:16",
        exit_hhmm="15:20",
        tilt="aggressive",
        smoothing=1.0,
        rebalance_every=1,
        capital=1_000_000.0,
        universe="all_equity",
        continuous_only=False,
        seed=0,
    )
    variant_config = dataclasses.replace(base_config, **{field_name: alt_value})
    contract = minimal_contract()  # SAME contract for both runs -- only TiltConfig differs.

    base_registry = TrialRegistry(tmp_path / f"reg_{field_name}_base.sqlite")
    variant_registry = TrialRegistry(tmp_path / f"reg_{field_name}_variant.sqlite")

    run_tilt(panel, base_config, contract=contract, registry=base_registry)
    run_tilt(panel, variant_config, contract=contract, registry=variant_registry)

    base_hash = base_registry.all(strategy="tilt")[0].config_hash
    variant_hash = variant_registry.all(strategy="tilt")[0].config_hash

    assert base_hash != variant_hash


def _four_smoothing_variants() -> tuple[list, list[datetime.date]]:
    dates = [datetime.date(2022, 1, 3) + datetime.timedelta(days=i) for i in range(5)]
    sessions = []
    for date in dates:
        entry_row = _flat_row(100.0)
        exit_row = entry_row + 0.01
        sessions.append((date, {"09:16": entry_row, "15:20": exit_row}))
    panel = _build_panel(sessions)

    base_config = TiltConfig(
        start=dates[0],
        end=dates[-1],
        tilt="aggressive",
        smoothing=0.10,
        rebalance_every=1,
        capital=1_000_000.0,
        seed=0,
    )
    configs = [
        base_config,
        dataclasses.replace(base_config, smoothing=1.0),
        dataclasses.replace(base_config, smoothing=0.5),
        dataclasses.replace(base_config, smoothing=0.25),
    ]
    return configs, panel


def test_o12_n_distinct_tilt_configs_on_same_split_yield_n_rows_not_fewer(tmp_path):
    """RED at HEAD: four distinct tilt configurations (differing only in `smoothing`, the
    coordinator's own +3.22/-9.41 bps example) recorded against one contract and one
    registry are silently collapsed to a single row, because config_hash ignores
    TiltConfig entirely and split_id is hard-coded to "full" inside run_tilt. This
    assertion is EXPECTED TO FAIL TODAY -- it is the regression test for the confirmed
    silent-drop defect, not a hypothetical."""
    configs, panel = _four_smoothing_variants()
    contract = minimal_contract()
    registry = TrialRegistry(tmp_path / "shared.sqlite")

    for config in configs:
        run_tilt(panel, config, contract=contract, registry=registry)

    assert len(registry.all(strategy="tilt")) == 4


def test_o13_registered_trial_count_matches_configs_actually_run(tmp_path):
    """RED at HEAD: n_trials() reports only the ONE surviving (config_hash, split_id) row
    instead of the four configurations actually run. This count is exactly what a real
    scheme comparison would feed into effective_n_trials/deflated Sharpe/PBO, so this
    silent undercount makes the multiple-testing correction too permissive. EXPECTED TO
    FAIL TODAY for the same confirmed defect as test_o12."""
    configs, panel = _four_smoothing_variants()
    contract = minimal_contract()
    registry = TrialRegistry(tmp_path / "shared.sqlite")

    for config in configs:
        run_tilt(panel, config, contract=contract, registry=registry)

    assert registry.n_trials(strategy="tilt", purpose="exploration") == 4
