name: all_equity
symbols:
- ABB
- ABCAPITAL
- ACC
- ADANIENSOL
- ADANIENT
- ADANIGREEN
- ADANIPORTS
- ADANIPOWER
- AMBUJACEM
- APOLLOHOSP
- ASHOKLEY
- ASIANPAINT
- ATGL
- AUROPHARMA
- AWL
- AXISBANK
- BAJAJ-AUTO
- BAJAJFINSV
- BAJAJHLDNG
- BAJFINANCE
- BANDHANBNK
- BANKBARODA
- BEL
- BERGEPAINT
- BHARTIARTL
- BHEL
- BIOCON
- BOSCHLTD
- BPCL
- BRITANNIA
- CANBK
- CGPOWER
- CHOLAFIN
- CIPLA
- COALINDIA
- COLPAL
- CONCOR
- CUMMINSIND
- DABUR
- DIVISLAB
- DLF
- DMART
- DRREDDY
- EICHERMOT
- EMAMILTD
- ENRIN
- ETERNAL
- GAIL
- GICRE
- GLAXO
- GLENMARK
- GODREJCP
- GRASIM
- HAL
- HAVELLS
- HCLTECH
- HDFCAMC
- HDFCBANK
- HDFCLIFE
- HEROMOTOCO
- HINDALCO
- HINDPETRO
- HINDUNILVR
- HINDZINC
- HYUNDAI
- ICICIBANK
- ICICIGI
- ICICIPRULI
- IDEA
- INDHOTEL
- INDIGO
- INDUSINDBK
- INDUSTOWER
- INFY
- IOC
- IRCTC
- IRFC
- ITC
- JINDALSTEL
- JIOFIN
- JSWSTEEL
- KOTAKBANK
- LICHSGFIN
- LICI
- LODHA
- LT
- LTM
- LUPIN
- M&M
- MARICO
- MARUTI
- MAXHEALTH
- MAZDOCK
- MOTHERSON
- MRF
- MUTHOOTFIN
- NAUKRI
- NESTLEIND
- NHPC
- NIACL
- NMDC
- NTPC
- NYKAA
- OFSS
- OIL
- ONGC
- PAGEIND
- PETRONET
- PFC
- PGHH
- PIDILITIND
- PIIND
- PNB
- POWERGRID
- RECLTD
- RELIANCE
- SAIL
- SBICARD
- SBILIFE
- SBIN
- SHREECEM
- SHRIRAMFIN
- SIEMENS
- SOLARINDS
- SRF
- SUNPHARMA
- SUNTV
- TATACAP
- TATACONSUM
- TATAPOWER
- TATASTEEL
- TCS
- TECHM
- TITAN
- TMCV
- TMPV
- TORNTPHARM
- TRENT
- TVSMOTOR
- ULTRACEMCO
- UNIONBANK
- UNITDSPR
- UPL
- VBL
- VEDL
- WIPRO
- YESBANK
- ZEEL
- ZYDUSLIFE
