name: liquid25
symbols:
- RELIANCE
- HDFCBANK
- ICICIBANK
- INFY
- TCS
- SBIN
- BHARTIARTL
- ITC
- AXISBANK
- LT
- KOTAKBANK
- HINDUNILVR
- BAJFINANCE
- MARUTI
- SUNPHARMA
- TITAN
- ULTRACEMCO
- NTPC
- POWERGRID
- TATAMOTORS
- TATASTEEL
- WIPRO
- ONGC
- JSWSTEEL
- ADANIPORTS
